name: Docker Image
on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker pull ubuntu
    
    - name: Run the Docker container
      run: |
        
      
        docker run -d --name safder ubuntu
        docker ps -a
        docker exec safder ps aux
        
        
